version: '2'
template:
  name: "Functions serverlessapppython"
  description: "Deploy your Cloud Functions for serverlessapppython app."
  required:
    - repo
    - build

toolchain:
  name: serverlessapppython

services:

  # Github repos
  repo:
    service_id: hostedgit
    parameters:
      repo_url: "{{#zip_url}}{{zip_url}}{{/zip_url}}{{^zip_url}}{{repository}}{{/zip_url}}"
      repo_name: "{{toolchain.name}}"
      type: clone
      has_issues: true
      enable_traceability: true

  # Pipelines
  build:
    service_id: pipeline
    parameters:
      services: 
        - repo
      name: "{{toolchain.name}}"
      ui-pipeline: true
      configuration:
        content: 
          $text: pipeline.yml
        env:
          REPO: repo
          CF_APP: "{{form.pipeline.parameters.app-name}}"
          CF_SPACE: "{{form.pipeline.parameters.dev-space}}"
          CF_ORGANIZATION: "{{form.pipeline.parameters.dev-organization}}"
          REGION_ID: "{{form.pipeline.parameters.dev-region}}"
        execute: true

  #Web IDE
  webide:
    service_id: orion

#Deployment
form:
  pipeline:
    schema:
      $ref: deploy.json
    parameters:
      app-name: serverlessapppython
      dev-space: "{{space}}"
      dev-organization: "{{organization}}"
      dev-region: "{{region}}"
